### PR TITLE
Implement correct SLEEP, handle value casting, fix security issues, and more

### LINKED ISSUE #29: Assigning value of type "float" to array of type "int"
Du är i hissen. Här finns tio knappar. Dom nio första är numrerade
1-9. På den sista står det NÖDSTOPP.
Vilken knapp trycker du på ? ? 10
Assigning value of type "float" to array of type "int"

### PR DESCRIPTION
**Pull request by jomag**
This commit has been in the works for a quite long time and unfortunately
involves quite a few, separate things:

- (Correctly) implements the `SLEEP` statement/function, with support for waking up on user input
- Updates a few packages with security issues
- Arrays have a type and can only be assigned values of same type
- Adds new ValueType: FLOAT. (`A$` is string, `A%` is int, `A` is float)
- Add new function, `castValue`, that handles casting value types and throws runtime error if illegal cast
- Fix problem with running modified programs in the shell
- Update all tests to use correct variable names depending on data type

This will likely fix #29.

### CODE REVIEW

File: src/support/node.js [hunk 1]
```diff
@@ -61,12 +62,37 @@ class Support extends BaseSupport {
     }
   }
 
+  waitForInput(timeout) {
+    let timeoutId;
+
+    return new Promise(resolve => {
+      const inputHandler = data => {
+        console.log('IN INPUT HANDLER: ', data);
```
Comment (jomag) [inline src/support/node.js:70]: remove

File: src/support/node.js [hunk 2]
```diff
@@ -61,12 +62,37 @@ class Support extends BaseSupport {
...
+        this.inputBuffer.push(data);
+        clearTimeout(timeoutId);
+        resolve(1);
+      };
+
+      this.rl.once('line', inputHandler);
+
+      timeoutId = setTimeout(() => {
+        console.log('IN TIMEOUT HANDLER');
```
Comment (jomag) [inline src/support/node.js:79]: remove

File: src/BasicFunction.js [hunk 3]
```diff
@@ -188,11 +186,12 @@ const asciiFun = args => {
   throw new IllegalFunctionCallError('Empty string');
 };
 
-const sleepFun = async ([seconds]) => {
+const sleepFun = async ([seconds], context) => {
   validateNumber(seconds);
   // FIXME: should be interrupted when user is typing any delimiter, such as return
-  await new Promise(resolve => setTimeout(resolve, seconds.value * 1000.0));
-  return new Value(ValueType.INT, 0);
+  // await new Promise(resolve => setTimeout(resolve, seconds.value * 1000.0));
```
Comment (jomag) [inline src/BasicFunction.js:192]: Hm, can't remember, need to test, but it seems like this has been fixed now.
